/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeshopproject;


import java.sql.*;
import javax.swing.*;
import java.io.File;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


    



/**
 *
 * @author Ryzen
 */
public class Profil_pelanggan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profil_pelanggan.class.getName());
    private String emailPengguna;
    private String selectedImagePath = null;


    public Profil_pelanggan() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
        setTitle("Profil Pelanggan");
}
    public Profil_pelanggan(String email) {
        initComponents();
        setSize(800, 600);              // atur ukuran form
        setLocationRelativeTo(null);    // tampil di tengah layar
        setTitle("Profil Pelanggan");   // ubah judul window
        this.emailPengguna = email;  // ✅ perbaikan di sini
        tampilkanDataPengguna();
}


   
    
    private void tampilkanDataPengguna() {
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            // koneksi ke database
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coffeeshop", "root", "");
            
            String sql = "SELECT nama, email, no_hp, tanggal_lahir FROM pengguna WHERE email = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, emailPengguna);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                lblNama.setText(rs.getString("nama"));
                lblEmail.setText("Email: " + rs.getString("email"));
                lblno_hp.setText("No HP: " + rs.getString("no_hp"));
                tanggal_lahir.setText("Tanggal_lahir: " + rs.getDate("tanggal_lahir"));
            } else {
                JOptionPane.showMessageDialog(this, "Data pengguna tidak ditemukan.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                logger.log(java.util.logging.Level.SEVERE, null, e);
            }
        }
    }
    

    /**
     *
     */
  

   

    // === Styling ===
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblno_hp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnpilihfoto = new javax.swing.JButton();
        tanggal_lahir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 217, 193));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(28, 28, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("tambahkan foto");
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0)));

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 215, 0));
        lblNama.setText("Nama");

        lblEmail.setText("email");

        lblno_hp.setText("no hp");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setLabel("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnpilihfoto.setText("PILIH FOTO");
        btnpilihfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihfotoActionPerformed(evt);
            }
        });

        tanggal_lahir.setText("tanggal lahir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnpilihfoto)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblNama))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblno_hp)
                            .addComponent(lblEmail)
                            .addComponent(tanggal_lahir))))
                .addGap(37, 302, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpilihfoto)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addGap(32, 32, 32)
                        .addComponent(lblno_hp)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(tanggal_lahir))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 800, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                           
    // Tutup form profil pelanggan
    this.dispose();
    
    // Buka kembali form login
    Login loginForm = new Login();
    loginForm.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpilihfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihfotoActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Pilih Foto Profil");

    // Hanya izinkan file gambar
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Gambar", "jpg", "png", "jpeg", "gif"
    ));

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        String filePath = file.getAbsolutePath();

        // Tampilkan gambar di JLabel lblAvatar
        ImageIcon icon = new ImageIcon(filePath);
        Image img = icon.getImage().getScaledInstance(lblAvatar.getWidth(), lblAvatar.getHeight(), Image.SCALE_SMOOTH);
        lblAvatar.setIcon(new ImageIcon(img));

        // Simpan path gambar ke variabel (bisa disimpan ke database nanti)
        selectedImagePath = filePath;
    }
    }//GEN-LAST:event_btnpilihfotoActionPerformed

    /**
     * @param args the command line arguments
     */

        //</editor-fold>

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpilihfoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblno_hp;
    private javax.swing.JLabel tanggal_lahir;
    // End of variables declaration//GEN-END:variables
    }
    



